import os
import re
import subprocess
import threading
from pathlib import Path
from . import config
from .nextjs import create_nextjs_project as _scaffold_nextjs


SVG_COLOR_RE = re.compile(r"stop-color:\s*rgb\((\d+),\s*(\d+),\s*(\d+)\)", re.IGNORECASE)
SVG_XML_RE = re.compile(r"(<svg[^>]*>)(.*?)</svg>", re.DOTALL | re.IGNORECASE)
BAD_PATTERNS_IN_APP_ROUTER = [
    ("<html", "Do not write <html> or <body> tags in Next.js App Router — they're generated by layout.tsx"),
    ("<body", "Do not write <html> or <body> tags in Next.js App Router — they're generated by layout.tsx"),
    ("layout=\"fill\"", "Use `fill` prop without `layout` in Next.js <Image> (layout=fill is legacy)"),
]


class ValidationError(ValueError):
    pass


class FileEditor:
    def __init__(self, print_fn=None):
        self.workspace = config.get_workspace()
        self.print_fn = print_fn

    def _resolve(self, path: str) -> Path:
        p = Path(path)
        if not p.is_absolute():
            p = self.workspace / p
        return p.resolve()

    def _validate_content(self, path: str, content: str) -> None:
        ext = Path(path).suffix.lower()

        if ext == ".svg":
            if not SVG_XML_RE.search(content):
                raise ValidationError(f"SVG content has malformed XML in {path}")
            colors = SVG_COLOR_RE.findall(content)
            if colors:
                all_white = all(
                    int(r) == 255 and int(g) == 255 and int(b) == 255
                    for r, g, b in colors
                )
                if all_white:
                    raise ValidationError(
                        f"SVG at {path} has all gradient stops set to white (255,255,255) — "
                        "use visible colors like rgb(59,130,246) / rgb(34,211,238) instead"
                    )

        is_layout_tsx = Path(path).name == "layout.tsx"

        if ext in (".tsx", ".jsx"):
            for pattern, msg in BAD_PATTERNS_IN_APP_ROUTER:
                if pattern in content:
                    # <html>/<body> are only OK in layout.tsx
                    if pattern in ("<html", "<body") and is_layout_tsx:
                        continue
                    raise ValidationError(f"{msg}. File: {path}")

    def read_file(self, path: str) -> str:
        full = self._resolve(path)
        if not full.exists():
            raise FileNotFoundError(f"File not found: {full}")
        return full.read_text(encoding="utf-8")

    def write_file(self, path: str, content: str) -> str:
        full = self._resolve(path)
        self._validate_content(path, content)
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content, encoding="utf-8")
        return f"Wrote {len(content)} bytes to {full}"

    def edit_file(self, path: str, old_string: str, new_string: str) -> str:
        full = self._resolve(path)
        if not full.exists():
            raise FileNotFoundError(f"File not found: {full}")
        content = full.read_text(encoding="utf-8")
        if old_string not in content:
            raise ValueError(f"old_string not found in {full}")
        if content.count(old_string) > 1:
            raise ValueError(f"Found multiple matches for old_string in {full}. Provide more context.")
        new_content = content.replace(old_string, new_string)
        self._validate_content(path, new_content)
        full.write_text(new_content, encoding="utf-8")
        return f"Edited {full}"

    def delete_file(self, path: str) -> str:
        full = self._resolve(path)
        if not full.exists():
            raise FileNotFoundError(f"File not found: {full}")
        if full.is_dir():
            full.rmdir()
            return f"Deleted directory: {full}"
        full.unlink()
        return f"Deleted file: {full}"

    def list_files(self, path: str = ".") -> str:
        full = self._resolve(path)
        if not full.exists() or not full.is_dir():
            raise NotADirectoryError(f"Not a directory: {full}")
        lines = []
        for entry in sorted(full.iterdir()):
            suffix = "/" if entry.is_dir() else ""
            lines.append(f"{entry.name}{suffix}")
        return "\n".join(lines)

    def run_command(self, command: str) -> str:
        process = subprocess.Popen(
            command,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            cwd=self.workspace,
            text=True,
            bufsize=1,
        )

        output_lines = []
        lock = threading.Lock()
        timeout = 120

        def read_stream():
            try:
                for line in iter(process.stdout.readline, ""):
                    with lock:
                        output_lines.append(line)
                    if self.print_fn:
                        self.print_fn(line.rstrip())
            except ValueError:
                pass
            finally:
                if process.stdout:
                    process.stdout.close()

        reader = threading.Thread(target=read_stream, daemon=True)
        reader.start()

        try:
            process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            return "Error: Command timed out after 120 seconds (likely waiting for interactive input). Always use non-interactive flags like -y or --yes."
        finally:
            reader.join(timeout=3)

        with lock:
            return "".join(output_lines) or "(no output)"

    def create_nextjs_project(self, project_name: str) -> str:
        dest = _scaffold_nextjs(str(self.workspace), project_name)
        return f"Next.js project created at {dest}\n\nTo install dependencies run:\n  cd {project_name}\n  npm install\n  npm run dev"

    def get_tool_definitions(self) -> list[dict]:
        return [
            {
                "type": "function",
                "function": {
                    "name": "read_file",
                    "description": "Read the contents of a file. ALWAYS use this before editing a file you haven't seen.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "description": "Relative or absolute file path (e.g. package.json)"}
                        },
                        "required": ["path"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "write_file",
                    "description": "Create a new file or overwrite an existing one. Content is validated for common mistakes (white SVGs, <html>/<body> in components).",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "description": "Relative or absolute file path"},
                            "content": {"type": "string", "description": "Full file content"},
                        },
                        "required": ["path", "content"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "edit_file",
                    "description": "Replace exact text in an existing file (single occurrence). New content is validated for common mistakes.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "description": "Relative or absolute file path"},
                            "old_string": {"type": "string", "description": "Text to replace"},
                            "new_string": {"type": "string", "description": "Replacement text"},
                        },
                        "required": ["path", "old_string", "new_string"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "delete_file",
                    "description": "Delete a file or empty directory",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "description": "Relative or absolute file path"},
                        },
                        "required": ["path"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "list_files",
                    "description": "List files and directories in a folder. ALWAYS call this first to understand the project structure.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "description": "Directory path, defaults to ."},
                        },
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "create_nextjs_project",
                    "description": "Scaffold a Next.js 14 project with TypeScript and Tailwind CSS. Use \".\" as project_name to create files in the current folder.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "project_name": {"type": "string", "description": "Directory name, or \".\" to scaffold in current folder"},
                        },
                        "required": ["project_name"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "run_command",
                    "description": "Execute a shell command in the workspace directory (e.g. npm install, yarn add, npx, git). IMPORTANT: commands that prompt for input will time out — always include -y/--yes flags.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "command": {"type": "string", "description": "Shell command to run (include -y or --yes flags to avoid interactive prompts)"},
                        },
                        "required": ["command"],
                    },
                },
            },
        ]

    def execute_tool(self, name: str, args: dict) -> str:
        try:
            match name:
                case "read_file":
                    return self.read_file(args["path"])
                case "write_file":
                    return self.write_file(args["path"], args["content"])
                case "edit_file":
                    return self.edit_file(args["path"], args["old_string"], args["new_string"])
                case "delete_file":
                    return self.delete_file(args["path"])
                case "list_files":
                    return self.list_files(args.get("path", "."))
                case "create_nextjs_project":
                    return self.create_nextjs_project(args["project_name"])
                case "run_command":
                    return self.run_command(args["command"])
                case _:
                    raise ValueError(f"Unknown tool: {name}")
        except ValidationError as e:
            return f"VALIDATION REJECTED: {e}"
