import os
from pathlib import Path


def create_nextjs_project(base_dir: str, project_name: str) -> str:
    dest = Path(base_dir) / project_name
    if dest.exists():
        raise FileExistsError(f"Directory '{dest}' already exists")

    files = _get_project_files(project_name)
    for rel_path, content in files.items():
        full = dest / rel_path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content, encoding="utf-8")

    return str(dest)


def _get_project_files(project_name: str) -> dict[str, str]:
    return {
        "package.json": _package_json(project_name),
        "next.config.ts": _next_config(),
        "tsconfig.json": _tsconfig(),
        "postcss.config.mjs": _postcss_config(),
        "tailwind.config.ts": _tailwind_config(),
        ".gitignore": _gitignore(),
        "public/.gitkeep": "",
        "app/layout.tsx": _layout(),
        "app/page.tsx": _page(),
        "app/globals.css": _globals_css(),
    }


def _package_json(name: str) -> str:
    return f'''\
{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "^14.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }},
  "devDependencies": {{
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.4.5"
  }}
}}
'''


def _next_config() -> str:
    return """\
/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
"""


def _tsconfig() -> str:
    return """\
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""


def _postcss_config() -> str:
    return """\
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
"""


def _tailwind_config() -> str:
    return """\
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
"""


def _gitignore() -> str:
    return """\
# dependencies
/node_modules
/.pnp
.pnp.js

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
"""


def _layout() -> str:
    return """\
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
"""


def _page() -> str:
    return """\
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
    </main>
  );
}
"""


def _globals_css() -> str:
    return """\
@tailwind base;
@tailwind components;
@tailwind utilities;
"""
