import json
from typing import Any
from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory
from prompt_toolkit.styles import Style
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from . import config
from .client import ModelscopeClient
from .editor import FileEditor
from .nextjs import create_nextjs_project

console = Console()
style = Style.from_dict({"prompt": "ansicyan bold"})


SYSTEM_PROMPT = """You are an AI coding assistant with access to these tools:

### File tools
- `read_file` — read file contents
- `write_file` — create/overwrite a file
- `edit_file` — replace exact text in a file (single match)
- `delete_file` — delete a file or empty directory
- `list_files` — list directory contents

### Project tools
- `create_nextjs_project` — scaffold a full Next.js 14 project with TypeScript + Tailwind (preferred over writing files manually)
- `run_command` — execute shell commands (e.g. npm install, yarn add, npx, git, etc.)

## CRITICAL: Always inspect before acting

Before ANY tool call, ALWAYS use `list_files` or `read_file` to understand the project.
Never assume what files exist or what is already configured. Always check.

## CRITICAL: Never run interactive commands

Commands that prompt for input will TIME OUT after 120 seconds. Always:
- Append `-y` or `--yes` to installers (npm, npx, pip, apt, etc.)
- Append `-f` to force operations
- NEVER run bare `npx shadcn@latest` or `npx shadcn init` — these hang
- NEVER run `npm init` without `-y`

## Next.js App Router rules (MANDATORY)

- NEVER write `<html>`, `<head>`, or `<body>` tags in any component — they are generated by `layout.tsx`
- NEVER use `layout="fill"` on Next.js <Image> — use `fill` prop directly
- ALWAYS check the existing `layout.tsx` and `page.tsx` before editing them
- SVG files should go in `public/` folder, not `src/`

## Shadcn UI

1. Check if `components.json` exists — if yes, shadcn IS ALREADY INITIALIZED. Use `npx shadcn add <component>`.
2. Only run `npx shadcn init` if `components.json` does NOT exist, and always with `-y`.
3. Do NOT install shadcn if `components.json`, `tailwind.css`, and shadcn deps already exist in package.json.

## SVG files

- ALWAYS use visible colors. Both gradient stops set to white (255,255,255) produces a blank image.
- Example working gradient: stop-color="rgb(59,130,246)" to stop-color="rgb(34,211,238)"
- Verify the SVG renders visibly before creating it.

## Example of correct workflow (follow this pattern)

1. Run `list_files` to see the project structure
2. Run `read_file` on `package.json` and relevant files
3. Only then decide what tools to call
4. Include a plan with `[x]`/`[ ]` markers showing progress

When asked to create a Next.js project, use `create_nextjs_project`. If the user says "inside this folder" or "in the current directory", use "." as the project_name. After scaffolding, use `run_command` to install dependencies.
Work in the user's workspace.

## Response format for multi-step tasks

When a task requires multiple steps, include a plan section in your response:

```
## Plan
- [x] Completed step
- [ ] Current step description
- [ ] Future step
```

Mark the current step with `[ ]` and completed steps with `[x]`.
Update the plan after each tool call so the user can see progress."""


def run() -> None:
    try:
        client = ModelscopeClient()
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        console.print(f"\nGet a token at: [cyan]{config.MODELSCOPE_TOKEN_URL}[/cyan]")
        return

    editor = FileEditor(print_fn=console.print)
    history = FileHistory(".chat_history")
    session = PromptSession(history=history)

    console.print(Panel.fit("Modelscope TUI — AI Coding Assistant", style="bold cyan"))
    console.print(f"Model: {config.get_model()}")
    console.print(f"Workspace: {editor.workspace}")
    console.print("Type /help for commands, /exit to quit.\n")

    messages: list[dict[str, Any]] = [{"role": "system", "content": SYSTEM_PROMPT}]

    while True:
        try:
            prompt = session.prompt("\nYou: ", style=style)
        except (EOFError, KeyboardInterrupt):
            console.print("\nBye!")
            break

        cmd = prompt.strip()

        if not cmd:
            continue

        if cmd == "/exit":
            console.print("Bye!")
            break

        if cmd == "/check":
            console.print("\n[bold]Connection check:[/bold]")
            console.print(client.check_connection())
            continue

        if cmd == "/help":
            console.print(Panel(
                "/exit    - quit\n"
                "/check   - test API connection\n"
                "/clear   - clear conversation\n"
                "/create-nextjs [name] - scaffold a Next.js project\n"
                "/model <name> - switch model\n"
                "/tools   - show available tools\n"
                "/workspace <dir> - change workspace\n"
                "Everything else is sent to the AI.",
                title="Commands",
            ))
            continue

        if cmd == "/clear":
            messages.clear()
            messages.append({"role": "system", "content": SYSTEM_PROMPT})
            console.print("[dim]Conversation cleared.[/dim]")
            continue

        if cmd == "/tools":
            for t in editor.get_tool_definitions():
                console.print(f"[bold cyan]{t['function']['name']}[/bold cyan]: {t['function']['description']}")
            continue

        if cmd.startswith("/model "):
            new_model = cmd[7:].strip()
            if new_model:
                import os
                os.environ["MODELSCOPE_MODEL"] = new_model
                client.model = new_model
                console.print(f"Switched to model: {new_model}")
            continue

        if cmd.startswith("/workspace "):
            new_ws = cmd[11:].strip()
            if new_ws:
                import os
                os.environ["WORKSPACE_DIR"] = new_ws
                editor.workspace = config.get_workspace()
                console.print(f"Workspace changed to: {editor.workspace}")
            continue

        if cmd.startswith("/create-nextjs"):
            parts = cmd.split(None, 1)
            name = parts[1].strip() if len(parts) > 1 else "my-app"
            try:
                dest = create_nextjs_project(editor.workspace, name)
                console.print(f"\n[bold green]Next.js project created at:[/bold green] {dest}")
                if name not in ("", "."):
                    console.print("\n[bold]To get started:[/bold]")
                    console.print(f"  cd {name}")
                    console.print("  npm install")
                    console.print("  npm run dev")
            except (FileExistsError, OSError) as e:
                console.print(f"\n[red]Error: {e}[/red]")
            continue

        messages.append({"role": "user", "content": cmd})

        while True:
            tool_call_cycle = len(messages) > 1 and any(m.get("role") == "tool" for m in messages[-3:])
            status_text = "Applying tool results..." if tool_call_cycle else "Thinking..."

            with console.status(status_text, spinner="dots"):
                try:
                    response = client.chat(messages, tools=editor.get_tool_definitions())
                except ValueError as e:
                    console.print(f"\n[red]{e}[/red]")
                    break
                except Exception as e:
                    console.print(f"\n[red]API error: {e}[/red]")
                    break

            choice = response["choices"][0]
            msg = choice["message"]

            reasoning = msg.get("reasoning_content", "") or ""
            if reasoning:
                console.print("\n[dim italic]Thinking:[/dim italic]")
                for line in reasoning.split("\n"):
                    console.print(f"[dim italic]{line}[/dim italic]")

            assistant_msg = {k: v for k, v in msg.items() if k != "reasoning_content"}

            tool_calls = assistant_msg.get("tool_calls")
            if not tool_calls:
                content = assistant_msg.get("content", "")
                if content:
                    console.print("\n[bold green]Assistant:[/bold green]")
                    console.print(Markdown(content))
                messages.append(assistant_msg)
                break

            msg_content = assistant_msg.get("content", "")
            if msg_content:
                console.print(Markdown(msg_content))

            messages.append(assistant_msg)

            for tc in tool_calls:
                fn = tc["function"]
                name = fn["name"]
                try:
                    args = json.loads(fn["arguments"])
                except json.JSONDecodeError as e:
                    args = {}
                    console.print(f"[red]JSON parse error in tool args: {e}[/red]")

                console.print(f"\n[bold yellow]Tool:[/bold yellow] {name}({args})")

                try:
                    result = editor.execute_tool(name, args)
                    console.print(f"[dim]{result[:500]}[/dim]")
                except Exception as e:
                    result = f"Error: {e}"
                    console.print(f"[red]{result}[/red]")

                messages.append({
                    "role": "tool",
                    "tool_call_id": tc["id"],
                    "content": result,
                })
